meta:
  version: 0.1.0

id: <ID>

start:
  command: ls
  arguments: []
  user: ubuntu

  after: []
  delay: 2s

restart:
  strategy: never
  attempts: 0

termination:
  command:
  arguments: []

  before: []
  delay: 2s

environment:
  clear: true
  variables: {}

log:
  stdin: /dev/null
  stdout: /dev/stdout
  stderr: /dev/stderr

diagnosis:
  level5: ''
  level4: ''
  level3: ''
  level2: ''
  level1: ''
